baseurl = "https://litegapps.github.io"
title = "The LiteGapps Open Source Project"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en"
resourceDir = "../resources"
DefaultContentLanguage = "en"

PygmentsCodeFences = true
PygmentsStyle      = "monokai"

[markup.goldmark.renderer]
  unsafe = true # agar bisa menulis html di markdown
  
buildFuture = true

[pagination]
  disableAliases = false
  pagerSize = 20
     
[sitemap]
  changefreq = "always"
  priority = 0.8
  filename = "sitemap.xml"
[permalinks]
   changelog     = ":section/:year/:slug"
   doc         = ":section/:year:month/:slug"
  
[outputs.taxonomy.removePath]
  tags = ["/tags"]
  categories = ["/categories"]
  